### ISSUE TITLE
Passion Vines not Progressing Beyond Flowering

### ISSUE THREAD

**Issue by JSJosh** [bageldotjpg/Atmospheric#14]
Now, I am not sure if I am just not understanding the description on curseforge, but passion vines never grow beyond flowering. I have grown them on oak leaves, oak logs, and floating in-air, and they have been up for so long with no progression. I have also not seen a single passion vine beyond flowering in the native rosewood biome.

**Comment by bageldotjpg** [comment]
They must be on Rosewood Logs or Leaves to grow past flowering

**Comment by JSJosh** [comment]
Probably should say that on the curseforge page. Still doesnt explain why I did not see a passionfruit vine actually grow beyond flowering even in the rosewood biome, but maybe I just wasn't there long enough?
