### ISSUE TITLE
Poison effect is desynced from server with the Gelled effect

### ISSUE THREAD

**Issue by Insane96** [bageldotjpg/Atmospheric#23]
![2020-06-01_10 41 42](https://user-images.githubusercontent.com/7185104/83391983-a55e7480-a3f4-11ea-9276-4f20fc214b17.png)
Sometimes get the effect but no damage and sometimes it never ends staying at 0 until world reload (So I think is a client-server desync)

**Comment by bageldotjpg** [comment]
Will be fixed in next update as of 4abc39bc3495db3cc84ccd076024b1a2a74d8717
