### ISSUE TITLE
Decorations placing on top of trees (possibly a BoP incompatability)

### ISSUE THREAD

**Issue by Dakedres** [bageldotjpg/Atmospheric#26]
When using Biomes o Plenty with Atmospheric I found that some flowers in the desert biomes would often spawn on top of the trees in the biome. This could be at fault to BoP.
![image](https://user-images.githubusercontent.com/36781227/84471982-b0f73a00-ac43-11ea-8bb4-35ed12aa5bc5.png)

**Comment by bageldotjpg** [comment]
No, this is completely intended. Yucca Flowers can grow on Yucca trees.

**Comment by Dakedres** [comment]
Ah, ok
