### ISSUE TITLE
Zombies trying to be cast to ServerPlayerEntity

### ISSUE THREAD

**Issue by Syndaryl** [bageldotjpg/Atmospheric#5]
[crash-2020-03-28_15.13.45-server.txt](https://github.com/bageldotjpg/Atmospheric/files/4397720/crash-2020-03-28_15.13.45-server.txt)

Can you put in a try-catch or test for heritability before this cast? It's crashing my game.

**Comment by bageldotjpg** [comment]
This is fixed in dev and will be fixed next release
