### ISSUE TITLE
issue #5 not fixed in 1.14

### ISSUE THREAD

**Issue by pabthelamb** [bageldotjpg/Atmospheric#7]
https://github.com/bageldotjpg/Atmospheric/issues/5 is not fixed in 1.1.2 on 1.14.4.
It crashes when I try to load the world.

**Comment by bageldotjpg** [comment]
Sorry, 1.14.4 isn't recieving support anymore... This also won't occur unless you give any other mobs the "Spitting" potion effect which isn't possible outside of Foxes or via commands
