### ISSUE TITLE
Wood Logs on Maps crash the game

### ISSUE THREAD

**Issue by Dralkkin** [bageldotjpg/Atmospheric#8]
Trying to generate a map with any type of Wood Log from the mod crashes the game with a 'java.lang.NullPointerException: Ticking player' exception.

[crash-2020-04-14_03.21.27-server.txt](https://github.com/bageldotjpg/Atmospheric/files/4474045/crash-2020-04-14_03.21.27-server.txt)

**Comment by bageldotjpg** [comment]
Fixed in https://github.com/bageldotjpg/Atmospheric/commit/70e69af9a42105991534e9dfd92aa7154e67e63c
